### Library import

In [53]:
import pandas as pd
import zstandard as zstd
import os
import numpy as np
import json
from collections import Counter

### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

Decompressing all the .zst files with the zstandard library and a loop repeating the process to all files ending with .csv.zst.

In [54]:
data_dir = "trendingYT"
output_dir = "csv-extraction"
os.makedirs(output_dir, exist_ok=True)
csv_zst_files = [f for f in os.listdir(data_dir) if f.endswith(".csv.zst")]

for file_name in csv_zst_files:
    file_path = os.path.join(data_dir, file_name)
    base_name = os.path.splitext(file_name)[0]
    csv_path = os.path.join(output_dir, base_name)
    with open(file_path, 'rb') as compressed:
        dctx = zstd.ZstdDecompressor()
        with open(csv_path, 'wb') as out_csv:
            out_csv.write(dctx.decompress(compressed.read()))

Creating the Country column for the Canada Dataframe. More info about the encoding choices later

In [55]:
df_ca = pd.read_csv(output_dir + "/CAvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_ca["country"] = "CA"

df_ca.info()
df_ca.head()

<class 'pandas.DataFrame'>
RangeIndex: 40881 entries, 0 to 40880
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40881 non-null  str
 1   trending_date           40881 non-null  str
 2   title                   40881 non-null  str
 3   channel_title           40881 non-null  str
 4   category_id             40881 non-null  int64
 5   publish_time            40881 non-null  str
 6   tags                    40881 non-null  str
 7   views                   40881 non-null  int64
 8   likes                   40881 non-null  int64
 9   dislikes                40881 non-null  int64
 10  comment_count           40881 non-null  int64
 11  thumbnail_link          40881 non-null  str
 12  comments_disabled       40881 non-null  bool
 13  ratings_disabled        40881 non-null  bool
 14  video_error_or_removed  40881 non-null  bool
 15  description             39585 non-null  str
 16  country                 40881 non-null  str
dtypes: bool(3), int64(5), str(9)
memory usage: 4.5 MB

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

We made multiple attempts to read and create the Dataframes for each contry, although the Japan one displayed an encoding problem.
We fixed by appliyng utf-8 as encoding format and replacing faulty cells. This choice also preserved the original japanese format of the object cells, which, for example, the latin1 encoding (which was suggested by many sources) didnt.

In [56]:
df_jp = pd.read_csv(output_dir + "/JPvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_jp["country"] = "JP"

df_jp.info()
df_jp.head()

<class 'pandas.DataFrame'>
RangeIndex: 20523 entries, 0 to 20522
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                20523 non-null  str
 1   trending_date           20523 non-null  str
 2   title                   20523 non-null  str
 3   channel_title           20523 non-null  str
 4   category_id             20523 non-null  int64
 5   publish_time            20523 non-null  str
 6   tags                    20523 non-null  str
 7   views                   20523 non-null  int64
 8   likes                   20523 non-null  int64
 9   dislikes                20523 non-null  int64
 10  comment_count           20523 non-null  int64
 11  thumbnail_link          20523 non-null  str
 12  comments_disabled       20523 non-null  bool
 13  ratings_disabled        20523 non-null  bool
 14  video_error_or_removed  20523 non-null  bool
 15  description             18399 non-null  str
 16  country                 20523 non-null  str
dtypes: bool(3), int64(5), str(9)
memory usage: 2.3 MB

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,5ugKfHgsmYw,18.07.02,陸自ヘリ、垂直に落下＝路上の車が撮影,時事通信映像センター,25,2018-02-06T03:04:37.000Z,"事故|""佐賀""|""佐賀県""|""ヘリコプター""|""ヘリ""|""自衛隊""|""墜落""|""落下""|""現...",188085,591,189,0,https://i.ytimg.com/vi/5ugKfHgsmYw/default.jpg,True,False,False,佐賀県神埼市の民家に墜落した陸上自衛隊のＡＨ６４Ｄ戦闘ヘリコプターが垂直に落下する様子を、近...,JP
1,ohObafdd34Y,18.07.02,イッテQ お祭り男宮川×手越 巨大ブランコ②,神谷えりな Kamiya Erina 2,1,2018-02-06T04:01:56.000Z,[none],90929,442,88,174,https://i.ytimg.com/vi/ohObafdd34Y/default.jpg,False,False,False,NaN,JP
2,aBr2kKAHN6M,18.07.02,Live Views of Starman,SpaceX,28,2018-02-06T21:38:22.000Z,[none],6408303,165892,2331,3006,https://i.ytimg.com/vi/aBr2kKAHN6M/default.jpg,False,False,False,NaN,JP
3,5wNnwChvmsQ,18.07.02,東京ディズニーリゾートの元キャストが暴露した秘密5選,アシタノワダイ,25,2018-02-06T06:08:49.000Z,アシタノワダイ,96255,1165,277,545,https://i.ytimg.com/vi/5wNnwChvmsQ/default.jpg,False,False,False,東京ディズニーリゾートの元キャストが暴露した秘密5選\n\nかたまりクリエイトさま\n【検証...,JP
4,B7J47qFvdsk,18.07.02,榮倉奈々、衝撃の死んだふり！映画『家に帰ると妻が必ず死んだふりをしています。』特報,シネマトゥデイ,1,2018-02-06T02:30:00.000Z,[none],108408,1336,74,201,https://i.ytimg.com/vi/B7J47qFvdsk/default.jpg,False,False,False,家に帰ってきたサラリーマンのじゅん（安田顕）は、玄関で血を出して倒れている妻ちえ（榮倉奈々）...,JP

We had previosly identified line 255 as faulty (video_id 3Xn7nGqiJCU), so we ran a succesful double check in order to see if it was still present.

In [57]:
df_jp.loc[250:260]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
250,DHEgmES0HfU,18.08.02,テラスハウス オープニング ニュー ドアーズ 山チャンネル Vol.7「正直に言います、尊敬...,Netflix Japan,24,2018-02-06T10:00:05.000Z,"ネットフリックス|""ネトフリ""|""半田悠人""|""NETFLIX""|""テラスハウス""|""テラハ...",72459,575,25,250,https://i.ytimg.com/vi/DHEgmES0HfU/default.jpg,False,False,False,【山チャンネル】Netflix公式チャンネル独占公開！山里亮太（南海キャンディーズ）による『...,JP
251,0ovTFlKXcy0,18.08.02,[SUPERSTAR SMTOWN]東方神起プレイ動画,SUPERSTAR SMTOWN,24,2018-02-07T05:23:59.000Z,"東方神起|""SUPERSTAR SMTOWN""|""KPOP""|""音ゲー""|""リズムゲーム""|...",31013,1326,25,63,https://i.ytimg.com/vi/0ovTFlKXcy0/default.jpg,False,False,False,☆東方神起グッズがあたるキャンペーン開催中☆\n\n人気KPOPゲーム【SUPERSTAR ...,JP
252,7UQSgAjKYdk,18.08.02,【7th WEEK】 みずき、元恋人に「早く会いたい…」,TERRACE HOUSE / テラスハウス,24,2018-02-06T09:00:01.000Z,"TERRACE HOUSE|""テラスハウス""|""テラハ""|""映画""|""劇場版""|""NETFL...",114223,332,128,0,https://i.ytimg.com/vi/7UQSgAjKYdk/default.jpg,True,False,False,いよいよテラスハウスの新シーズンがNETFLIXにて配信スタート！ \nその未公開映像をYo...,JP
253,3Xn7nGqiJCU,18.08.02,Why Trump Doesn't Want To Talk To Robert Mueller,The Late Show with Stephen Colbert,24,2018-02-07T08:35:00.000Z,"The Late Show|""Stephen Colbert""|""Colbert""|""Lat...",957641,14094,267,1036,https://i.ytimg.com/vi/3Xn7nGqiJCU/default.jpg,False,False,False,With Trump still undecided about sitting down ...,JP
254,U7pzUOdzYYk,18.08.02,有賀さつき 病気が判明。独りで病魔と戦った決死の覚悟の理由に涙が止まらない…,刺さるニュース,22,2018-02-06T09:00:03.000Z,"刺さるニュース|""UCXYFibd4JtRzi-SsWCvcwww""|""有賀さつき""|""フジ...",223959,321,291,30,https://i.ytimg.com/vi/U7pzUOdzYYk/default.jpg,False,False,False,★チャンネル登録はこちらからお願いいたします★\n⇒https://www.youtube....,JP
255,Fmx-IEa83JU,18.08.02,2018-2-7-01【仮想通貨の投資方法は５つある】視聴者様から家庭用ビデオカメラが届きま...,【コンサルユーチューバー】「法令遵守」「セキュリティ」「ICO資金調達」経営コンサルタント・...,29,2018-02-07T07:49:10.000Z,[none],7757,123,26,24,https://i.ytimg.com/vi/Fmx-IEa83JU/default.jpg,False,False,False,★中野裕二へのご質問や仮想通貨取引所のパソコン設定（スマホ、タブレットも設定します）、人生相...,JP
256,U9Tkv9FjyNw,18.08.02,星野みなみ年表がおもしろすぎるwwww 乃木坂46,最新46と 48,22,2018-02-06T11:56:54.000Z,[none],156835,2555,37,493,https://i.ytimg.com/vi/U9Tkv9FjyNw/default.jpg,False,False,False,NaN,JP
257,NwkoKEOUYaA,18.08.02,猫の噛み癖が治ったと錯覚したあの夜,コロン BB,15,2018-02-07T07:00:01.000Z,"コロンBB|""ライス""|""猫""|""子猫""|""子供""|""面白""|""癒し""|""可愛い""|""ぬこ""...",12442,570,6,103,https://i.ytimg.com/vi/NwkoKEOUYaA/default.jpg,False,False,False,ハメられた,JP
258,T17xaPhX5dU,18.08.02,2/6!!1日千円!!インを頼りに今日も勝つ!!【競艇エブリディ029】,競艇エブリディ,24,2018-02-06T19:03:02.000Z,"競艇|""競艇予想""|""ギャンブル""|""ボートレース""|""競馬""|""競艇エブリディ""|""一日千...",10068,121,13,44,https://i.ytimg.com/vi/T17xaPhX5dU/default.jpg,False,False,False,【競艇エブリディ】\nその名の通り毎日配信予定\n\n少ない投資を心がけてますが\nヒートア...,JP
259,2X6O10gGfzQ,18.08.02,AND MESHのiPhoneX用ケースが新発売！やっと出た人気メッシュデザイン,Appleが大好きなんだよ,26,2018-02-07T08:30:24.000Z,"iPhone X|""AND MESH""|""アンドメッシュ""|""グラデーション""|""iPhon...",7198,112,17,72,https://i.ytimg.com/vi/2X6O10gGfzQ/default.jpg,False,False,False,ずっと今か今かと待っていた方もいらっしゃるのではないでしょうか。\nそのデザインでずっと人気...,JP
260,wbSwFU6tY1c,18.08.02,Falcon Heavy Test Flight,SpaceX,28,2018-02-06T21:03:04.000Z,[none],14816949,300314,7802,30313,https://i.ytimg.com/vi/wbSwFU6tY1c/default.jpg,False,False,False,"When Falcon Heavy lifts off, it will be the mo...",JP

While manually checking the dataframe, we noticed that many lines were duplicates! We will have to take this aspect in consideration later.

In [58]:
df_jp[ df_jp['video_id'] == 'DHEgmES0HfU' ]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
162,DHEgmES0HfU,18.08.02,テラスハウス オープニング ニュー ドアーズ 山チャンネル Vol.7「正直に言います、尊敬...,Netflix Japan,24,2018-02-06T10:00:05.000Z,"ネットフリックス|""ネトフリ""|""半田悠人""|""NETFLIX""|""テラスハウス""|""テラハ...",72459,575,25,250,https://i.ytimg.com/vi/DHEgmES0HfU/default.jpg,False,False,False,【山チャンネル】Netflix公式チャンネル独占公開！山里亮太（南海キャンディーズ）による『...,JP
206,DHEgmES0HfU,18.08.02,テラスハウス オープニング ニュー ドアーズ 山チャンネル Vol.7「正直に言います、尊敬...,Netflix Japan,24,2018-02-06T10:00:05.000Z,"ネットフリックス|""ネトフリ""|""半田悠人""|""NETFLIX""|""テラスハウス""|""テラハ...",72459,575,25,250,https://i.ytimg.com/vi/DHEgmES0HfU/default.jpg,False,False,False,【山チャンネル】Netflix公式チャンネル独占公開！山里亮太（南海キャンディーズ）による『...,JP
250,DHEgmES0HfU,18.08.02,テラスハウス オープニング ニュー ドアーズ 山チャンネル Vol.7「正直に言います、尊敬...,Netflix Japan,24,2018-02-06T10:00:05.000Z,"ネットフリックス|""ネトフリ""|""半田悠人""|""NETFLIX""|""テラスハウス""|""テラハ...",72459,575,25,250,https://i.ytimg.com/vi/DHEgmES0HfU/default.jpg,False,False,False,【山チャンネル】Netflix公式チャンネル独占公開！山里亮太（南海キャンディーズ）による『...,JP
294,DHEgmES0HfU,18.08.02,テラスハウス オープニング ニュー ドアーズ 山チャンネル Vol.7「正直に言います、尊敬...,Netflix Japan,24,2018-02-06T10:00:05.000Z,"ネットフリックス|""ネトフリ""|""半田悠人""|""NETFLIX""|""テラスハウス""|""テラハ...",72459,575,25,250,https://i.ytimg.com/vi/DHEgmES0HfU/default.jpg,False,False,False,【山チャンネル】Netflix公式チャンネル独占公開！山里亮太（南海キャンディーズ）による『...,JP

We finally created separate dataFrames for each Country, while adding the Country column

In [59]:
df_de = pd.read_csv(output_dir + "/DEvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_de["country"] = "DE"

df_fr = pd.read_csv(output_dir + "/FRvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_fr["country"] = "FR"

df_gb = pd.read_csv(output_dir + "/GBvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_gb["country"] = "GB"

df_in = pd.read_csv(output_dir + "/INvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_in["country"] = "IN"

df_jp = pd.read_csv(output_dir + "/JPvideos.csv", encoding = "utf-8", encoding_errors = "replace" )
df_jp["country"] = "JP"

df_kr = pd.read_csv(output_dir + "/KRvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_kr["country"] = "KR"

df_mx = pd.read_csv(output_dir + "/MXvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_mx["country"] = "MX"

df_ru = pd.read_csv(output_dir + "/RUvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_ru["country"] = "RU"

df_us = pd.read_csv(output_dir + "/USvideos.csv", encoding = "utf-8", encoding_errors = "replace")
df_us["country"] = "US"

Here we concatenate all the Data Frames, and move the result to a new, empty one. We had to specify the format of each column of the new dataframes, which otherwise would have been lost.
We used a simple dictionary technique, with the keys as the column names, each paired with their format as value.

In [60]:
list_df = [df_ca, df_jp, df_de, df_fr, df_gb, df_in, df_kr, df_mx, df_ru, df_us]
col_names = list_df[0].columns
col_types = list_df[0].dtypes.to_dict()
df_result = pd.DataFrame({col: pd.Series(dtype=col_types[col]) for col in col_names})

for df in list_df:
    df_result = pd.concat([df_result, df])

df_result = df_result.reset_index(drop=True)

df_result.info()
df_result.head()

<class 'pandas.DataFrame'>
RangeIndex: 375942 entries, 0 to 375941
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                375942 non-null  str
 1   trending_date           375942 non-null  str
 2   title                   375942 non-null  str
 3   channel_title           375942 non-null  str
 4   category_id             375942 non-null  int64
 5   publish_time            375942 non-null  str
 6   tags                    375942 non-null  str
 7   views                   375942 non-null  int64
 8   likes                   375942 non-null  int64
 9   dislikes                375942 non-null  int64
 10  comment_count           375942 non-null  int64
 11  thumbnail_link          375942 non-null  str
 12  comments_disabled       375942 non-null  bool
 13  ratings_disabled        375942 non-null  bool
 14  video_error_or_removed  375942 non-null  bool
 15  description             356464 non-null  str
 16  country                 375942 non-null  str
dtypes: bool(3), int64(5), str(9)
memory usage: 41.2 MB

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

Checkin results

In [61]:
for df in list_df:
    print(df.shape)

print("")
total_rows = sum(df.shape[0] for df in list_df)
print("total rows: ", total_rows)

(40881, 17)
(20523, 17)
(40840, 17)
(40724, 17)
(38916, 17)
(37352, 17)
(34567, 17)
(40451, 17)
(40739, 17)
(40949, 17)

total rows:  375942

### 2. Extract all videos that have no tag.

Here we create a new dataframe supposed to contain all videos with no Tag. We tried both by checking for nulls and for entryes with tags shorter than 1 characters. In both cases, the dataframe resulted empty, confirming no missing value.

    CORRECTED AFTER COMPLETING POINT 8

In [62]:
# df_null_tag = df_result[df_result['tags'].isna()]

# df_null_tag = df_result[df_result['tags'].str.len() <= 1]

df_null_tag = df_result[df_result['tags'] == '[none]']

df_null_tag.info()
df_null_tag.head()

<class 'pandas.DataFrame'>
Index: 37698 entries, 41 to 375938
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37698 non-null  str
 1   trending_date           37698 non-null  str
 2   title                   37698 non-null  str
 3   channel_title           37698 non-null  str
 4   category_id             37698 non-null  int64
 5   publish_time            37698 non-null  str
 6   tags                    37698 non-null  str
 7   views                   37698 non-null  int64
 8   likes                   37698 non-null  int64
 9   dislikes                37698 non-null  int64
 10  comment_count           37698 non-null  int64
 11  thumbnail_link          37698 non-null  str
 12  comments_disabled       37698 non-null  bool
 13  ratings_disabled        37698 non-null  bool
 14  video_error_or_removed  37698 non-null  bool
 15  description             26189 non-null  str
 16  country                 37698 non-null  str
dtypes: bool(3), int64(5), str(9)
memory usage: 4.4 MB

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA

### 3. For each channel, determine the total number of views

We decided to keep only one video in order to not count duplicated views

In [63]:
df_result['trending_date'] = pd.to_datetime(df_result['trending_date'], format='%y.%d.%m')
df_result_ordered = df_result.sort_values(by=['trending_date'], ascending=[True])
df_no_video_dup = df_result_ordered.drop_duplicates(subset=['video_id'], keep='last').reset_index(drop=True)
df_no_video_dup.info()

<class 'pandas.DataFrame'>
RangeIndex: 184287 entries, 0 to 184286
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                184287 non-null  str
 1   trending_date           184287 non-null  datetime64[us]
 2   title                   184287 non-null  str
 3   channel_title           184287 non-null  str
 4   category_id             184287 non-null  int64
 5   publish_time            184287 non-null  str
 6   tags                    184287 non-null  str
 7   views                   184287 non-null  int64
 8   likes                   184287 non-null  int64
 9   dislikes                184287 non-null  int64
 10  comment_count           184287 non-null  int64
 11  thumbnail_link          184287 non-null  str
 12  comments_disabled       184287 non-null  bool
 13  ratings_disabled        184287 non-null  bool
 14  video_error_or_removed  184287 non-null  bool
 15  description             171180 non-null  str
 16  country                 184287 non-null  str
dtypes: bool(3), datetime64[us](1), int64(5), str(8)
memory usage: 20.2 MB

In [64]:
total_views = df_no_video_dup.groupby('channel_title')['views'].sum()
print(total_views)

total_views.to_csv('total_views_per_channel.csv')

channel_title
! 세상에 무슨일이                1052789
!!8時だよ面白ネタ大集合               50207
!BTS・TWICE まとめ               7310
!Los amorosos Virales¡       6069
!t Live                    194690
                           ...
５分でできる DIY                 183245
ＢＡＳＨｔｖ                     116292
Ｋのフィッシングちゃんねる               37165
ＷＡＪＯＩＫＡ                    424129
💜Sandrea                   188204
Name: views, Length: 37577, dtype: int64

### 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [65]:
df_excluded = df_result[((df_result['comments_disabled'] == True) & (df_result['ratings_disabled'] == True)) | (df_result['video_error_or_removed'] == True)]
df_excluded.info()
df_excluded.head()

# create an excel to analyze if the algorithm is correct
# df_excluded.to_excel('excluded_videos.xlsx', index=False)

<class 'pandas.DataFrame'>
Index: 2620 entries, 173 to 369587
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                2620 non-null   str
 1   trending_date           2620 non-null   datetime64[us]
 2   title                   2620 non-null   str
 3   channel_title           2620 non-null   str
 4   category_id             2620 non-null   int64
 5   publish_time            2620 non-null   str
 6   tags                    2620 non-null   str
 7   views                   2620 non-null   int64
 8   likes                   2620 non-null   int64
 9   dislikes                2620 non-null   int64
 10  comment_count           2620 non-null   int64
 11  thumbnail_link          2620 non-null   str
 12  comments_disabled       2620 non-null   bool
 13  ratings_disabled        2620 non-null   bool
 14  video_error_or_removed  2620 non-null   bool
 15  description             2307 non-null   str
 16  country                 2620 non-null   str
dtypes: bool(3), datetime64[us](1), int64(5), str(8)
memory usage: 314.7 KB

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
173,H8IWLEtFt9A,2017-11-14,Intégrale - On n'est pas couché 11 novembre 20...,On n'est pas couché,24,2017-11-12T01:44:07.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",122282,0,0,0,https://i.ytimg.com/vi/H8IWLEtFt9A/default.jpg,True,True,False,Intégrale - On n'est pas couché 11 novembre 20...,CA
1069,om-_yJaSW_Y,2017-11-19,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",523258,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1278,om-_yJaSW_Y,2017-11-20,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1004809,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1320,faJOpxEyTWk,2017-11-20,Intégrale - On n'est pas couché 18 novembre 20...,On n'est pas couché,24,2017-11-19T02:01:15.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",87544,0,0,0,https://i.ytimg.com/vi/faJOpxEyTWk/default.jpg,True,True,False,Intégrale - On n'est pas couché 18 novembre 20...,CA
1573,om-_yJaSW_Y,2017-11-21,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1197269,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA

Checking original situation

In [66]:
df_result[['comments_disabled', 'ratings_disabled', 'video_error_or_removed']].value_counts()

comments_disabled  ratings_disabled  video_error_or_removed
False              False             False                     362285
True               False             False                       6096
False              True              False                       4941
True               True              False                       2367
False              False             True                         253
Name: count, dtype: int64

In [67]:
df_no_excluded = df_result[~(((df_result['comments_disabled'] == True) & (df_result['ratings_disabled'] == True)) | (df_result['video_error_or_removed'] == True))]

df_no_excluded.info()
df_no_excluded.head()

<class 'pandas.DataFrame'>
Index: 373322 entries, 0 to 375941
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                373322 non-null  str
 1   trending_date           373322 non-null  datetime64[us]
 2   title                   373322 non-null  str
 3   channel_title           373322 non-null  str
 4   category_id             373322 non-null  int64
 5   publish_time            373322 non-null  str
 6   tags                    373322 non-null  str
 7   views                   373322 non-null  int64
 8   likes                   373322 non-null  int64
 9   dislikes                373322 non-null  int64
 10  comment_count           373322 non-null  int64
 11  thumbnail_link          373322 non-null  str
 12  comments_disabled       373322 non-null  bool
 13  ratings_disabled        373322 non-null  bool
 14  video_error_or_removed  373322 non-null  bool
 15  description             354157 non-null  str
 16  country                 373322 non-null  str
dtypes: bool(3), datetime64[us](1), int64(5), str(8)
memory usage: 43.8 MB

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

Checking results

In [68]:
df_no_excluded[['comments_disabled', 'ratings_disabled', 'video_error_or_removed']].value_counts()

comments_disabled  ratings_disabled  video_error_or_removed
False              False             False                     362285
True               False             False                       6096
False              True              False                       4941
Name: count, dtype: int64

### 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

Checking presence of 0 dislikes, in order to avoid division by 0

In [69]:
df_no_excluded[df_no_excluded['dislikes'] == 0]
# it is strange that there are videos with 0 dislikes in trending youtube videos, probably botting problems

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
67,amEZKmJQ4Io,2017-11-14,Drako - Watch Me Do It [Official Video],babygranderecords,10,2017-10-23T19:38:36.000Z,"Drako|""Watch Me Do It""|""watch me""|""migos""|""dap...",25887,0,0,6,https://i.ytimg.com/vi/amEZKmJQ4Io/default.jpg,False,True,False,PURCHASE / STREAM WATCH ME DO IT https://fanli...,CA
161,bsgocWaULIU,2017-11-14,Troydon bent - Jam African,Troydon bent,10,2016-12-08T19:29:25.000Z,New Danchall music world reggae traditional so...,16921,187,0,5,https://i.ytimg.com/vi/bsgocWaULIU/default.jpg,False,False,False,Troydon bent performing Jam African produced b...,CA
235,wDEA3rpYHnI,2017-11-15,Marie-Louise Arsenault réplique à Denise Bomba...,TV Classics,22,2017-11-13T01:26:37.000Z,Marie-Louise Arsenault qui réplique à Denise B...,15800,88,0,0,https://i.ytimg.com/vi/wDEA3rpYHnI/default.jpg,True,False,False,Moment favori à la télé québécoise: Marie-Loui...,CA
271,LfajgipdxmA,2017-11-15,How does Yoonla work? Learning CPA,Anthonys Digital Lifestyle Dotcom,22,2017-11-14T10:57:38.000Z,"How does Yoonla work|""free work from home""|""le...",11810,1,0,0,https://i.ytimg.com/vi/LfajgipdxmA/default.jpg,False,False,False,How does Yoonla work? Learning CPA marketing t...,CA
313,8sdQ7dP9Drs,2017-11-15,"Today's News: It's On - Get The Goods, Novembe...",Whistler Blackcomb,17,2017-11-14T18:18:21.000Z,[none],4851,31,0,0,https://i.ytimg.com/vi/8sdQ7dP9Drs/default.jpg,False,False,False,Today’s news: it’s on. Whistler Mountain will ...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358439,8WbxbqwdWog,2018-03-13,Camera Goes on Japanese Sushi Conveyor Belt Sh...,TkyoSam,22,2018-03-06T16:18:30.000Z,"東京サム|""jvlog""|""jvlogger""|""tkyosam""|""tokyo""|""sam...",639517,0,0,1059,https://i.ytimg.com/vi/8WbxbqwdWog/default.jpg,False,True,False,I will call this video A Camera's Journey Thro...,US
360544,zkrq7Kpd1so,2018-03-24,ULTRA LIVE presents Ultra Music Festival 2018 ...,UMF TV,10,2018-03-24T07:55:21.000Z,"ultra music festival|""umf""|""mix""|""relive""|""aft...",1648886,0,0,548,https://i.ytimg.com/vi/zkrq7Kpd1so/default.jpg,False,True,False,Tune in here for the Ultra Music Festival 2018...,US
363543,9TUBf6l7FBg,2018-04-14,Coachella 2018 LIVE Channel 1,Coachella,10,2018-04-05T06:48:28.000Z,[none],3598220,0,0,0,https://i.ytimg.com/vi/9TUBf6l7FBg/default_liv...,False,True,False,For more cameras and VR180 immersive experienc...,US
363744,9TUBf6l7FBg,2018-04-15,Coachella 2018 LIVE Channel 1,Coachella,10,2018-04-05T06:48:28.000Z,[none],11137071,0,0,2,https://i.ytimg.com/vi/9TUBf6l7FBg/default_liv...,False,True,False,For more cameras and VR180 immersive experienc...,US
363948,9TUBf6l7FBg,2018-04-16,Coachella 2018 LIVE Channel 1,Coachella,10,2018-04-05T06:48:28.000Z,[none],24004779,0,0,3,https://i.ytimg.com/vi/9TUBf6l7FBg/default_liv...,False,True,False,For more cameras and VR180 immersive experienc...,US

The code with the for loop caused `ValueError: The truth value of a Series is ambiguous` because

a boolean expression on a Series cannot be used directly in an if statement

We use np.where() for a vectorized approach that applies the condition to all rows simultaneously

In [70]:
# for i in range(len(df_no_excluded)):
#     if df_no_excluded['dislikes'] == 0:
#         df_no_excluded['like_ratio'] = df_no_excluded['likes']
#     else:
#         df_no_excluded['like_ratio'] = df_no_excluded['likes'] / df_no_excluded['dislikes']

# df_no_excluded.head()


df_no_excluded['like_ratio'] = np.where(
    df_no_excluded['dislikes'] == 0,
    df_no_excluded['likes'], 
    df_no_excluded['likes'] / df_no_excluded['dislikes']
)
df_no_excluded.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044

Checking records with 0 dislikes

In [71]:
df_no_excluded[df_no_excluded['dislikes'] == 0].head(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
67,amEZKmJQ4Io,2017-11-14,Drako - Watch Me Do It [Official Video],babygranderecords,10,2017-10-23T19:38:36.000Z,"Drako|""Watch Me Do It""|""watch me""|""migos""|""dap...",25887,0,0,6,https://i.ytimg.com/vi/amEZKmJQ4Io/default.jpg,False,True,False,PURCHASE / STREAM WATCH ME DO IT https://fanli...,CA,0.0
161,bsgocWaULIU,2017-11-14,Troydon bent - Jam African,Troydon bent,10,2016-12-08T19:29:25.000Z,New Danchall music world reggae traditional so...,16921,187,0,5,https://i.ytimg.com/vi/bsgocWaULIU/default.jpg,False,False,False,Troydon bent performing Jam African produced b...,CA,187.0
235,wDEA3rpYHnI,2017-11-15,Marie-Louise Arsenault réplique à Denise Bomba...,TV Classics,22,2017-11-13T01:26:37.000Z,Marie-Louise Arsenault qui réplique à Denise B...,15800,88,0,0,https://i.ytimg.com/vi/wDEA3rpYHnI/default.jpg,True,False,False,Moment favori à la télé québécoise: Marie-Loui...,CA,88.0
271,LfajgipdxmA,2017-11-15,How does Yoonla work? Learning CPA,Anthonys Digital Lifestyle Dotcom,22,2017-11-14T10:57:38.000Z,"How does Yoonla work|""free work from home""|""le...",11810,1,0,0,https://i.ytimg.com/vi/LfajgipdxmA/default.jpg,False,False,False,How does Yoonla work? Learning CPA marketing t...,CA,1.0
313,8sdQ7dP9Drs,2017-11-15,"Today's News: It's On - Get The Goods, Novembe...",Whistler Blackcomb,17,2017-11-14T18:18:21.000Z,[none],4851,31,0,0,https://i.ytimg.com/vi/8sdQ7dP9Drs/default.jpg,False,False,False,Today’s news: it’s on. Whistler Mountain will ...,CA,31.0

### 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

We thought that using the non-duplicate database was the best option to obtain more accurate stats for points 6 and 7

In [72]:
# cast publish_time to datetime
df_no_video_dup['publish_time'] = pd.to_datetime(df_no_video_dup['publish_time'])

after testing and visualizing the effects of the algorithm directly on the dataset, we created the final function

In [73]:
# testing algorithm
# df_nodup['publish_min'] = df_nodup['publish_time'].dt.strftime('%M')

# df_nodup['publish_min_unit'] = df_nodup['publish_min'].astype(int) % 10

# df_nodup['inferior_lim'] = df_nodup['publish_min'].astype(int) - df_nodup['publish_min_unit']

# df_nodup['superior_lim'] = df_nodup['inferior_lim'] + 10

# df_nodup['raw_cluster'] = "from " + df_nodup['publish_time'].dt.strftime('%H') + ":" + df_nodup['inferior_lim'].astype(str).str.zfill(2) + " to " + df_nodup['publish_time'].dt.strftime('%H') + ":" + df_nodup['superior_lim'].astype(str).str.zfill(2)

# df_nodup['cluster'] = np.where(
#     df_nodup['superior_lim'].astype(int) == 60,
#     "from " + df_nodup['publish_time'].dt.strftime('%H') + ":" + df_nodup['inferior_lim'].astype(str).str.zfill(2) + " to " + (df_nodup['publish_time'] + pd.Timedelta(hours=1)).dt.strftime('%H') + ":00", 
#     "from " + df_nodup['publish_time'].dt.strftime('%H') + ":" + df_nodup['inferior_lim'].astype(str).str.zfill(2) + " to " + df_nodup['publish_time'].dt.strftime('%H') + ":" + df_nodup['superior_lim'].astype(str).str.zfill(2)
# )

# df_nodup.drop(columns=['publish_min', 'inferior_lim', 'superior_lim', 'publish_min_unit', 'raw_cluster'], inplace=True)

In [74]:
def create_time_cluster(df, publish_time_col='publish_time', cluster_col='cluster'):

    publish_time = df[publish_time_col]
    
    # extract minutes
    minutes = publish_time.dt.minute.astype(int)
    
    # extract minutes unit
    min_unit = minutes % 10
    
    # calculate limits of the cluster
    inferior_lim = minutes - min_unit
    superior_lim = inferior_lim + 10
    
    # extract hours
    hours = publish_time.dt.strftime('%H')
    
    # create final cluster handling the case when superior_lim == 60
    df[cluster_col] = np.where(
        superior_lim == 60,
        "from " + hours + ":" + inferior_lim.astype(str).str.zfill(2) + " to " + (publish_time + pd.Timedelta(hours=1)).dt.strftime('%H') + ":00", 
        "from " + hours + ":" + inferior_lim.astype(str).str.zfill(2) + " to " + hours + ":" + superior_lim.astype(str).str.zfill(2)
    )
    
    return df


df_no_video_dup = create_time_cluster(df_no_video_dup)
df_no_video_dup.head(20)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,cluster
0,y5wvD7QH1x4,2017-11-14,20 Chistes malos que te harán reír #12,ElJamesHD Tops,24,2017-11-12 19:00:04+00:00,"20 Chistes malos que te harán reír|""chistes ma...",299832,44011,1213,14355,https://i.ytimg.com/vi/y5wvD7QH1x4/default.jpg,False,False,False,Descarga la app: http://bit.do/ElJamesHDTops_Y...,MX,from 19:00 to 19:10
1,IZRJsmfscIg,2017-11-14,Lomo En Salsa de mostaza sin Horno,Armando En Tu Cocina,26,2017-11-13 17:01:14+00:00,"lomo de cerdo en salsa de moztaza|""armando en ...",14409,2419,17,441,https://i.ytimg.com/vi/IZRJsmfscIg/default.jpg,False,False,False,Les dejo este delicioso lomo de cerdo en salsa...,MX,from 17:00 to 17:10
2,URnaV-AK4og,2017-11-14,Le Lloran al INE Margarita Zavala y El Bronco ...,Campechaneando,25,2017-11-13 01:36:29+00:00,"peña nieto|""epn""|""amlo""|""lopez obrador""|""marga...",31974,2663,50,500,https://i.ytimg.com/vi/URnaV-AK4og/default.jpg,False,False,False,Los independientes piden más tiempo al INE ¡Po...,MX,from 01:30 to 01:40
3,s-VstUmpPzM,2017-11-14,TERREMOTO 7.6 EN IRAK 2017 ALERTA MUNDIAL,ALERTA MUNDIAL,22,2017-11-12 20:35:38+00:00,[none],34707,97,28,24,https://i.ytimg.com/vi/s-VstUmpPzM/default.jpg,False,False,False,NaN,MX,from 20:30 to 20:40
4,OIBG99riACs,2017-11-14,TEXTO DIARIO ANIMADO 13 de noviembre 2017,TextoDiarioAnimado,27,2017-11-13 03:57:01+00:00,"texto diario|""animado""|""jw.org""",8090,262,3,4,https://i.ytimg.com/vi/OIBG99riACs/default.jpg,False,False,False,Lunes 13 de noviembre. Verán al Hijo del hombr...,MX,from 03:50 to 04:00
5,5Dimg9RM4Lo,2017-11-14,Maru Dueñas le escribió un último mensaje a An...,Los Capitanes HD Capellan,24,2017-11-12 11:47:26+00:00,"Maru Dueñas|""escribió""|""último mensaje""|""Angel...",87525,171,37,11,https://i.ytimg.com/vi/5Dimg9RM4Lo/default.jpg,False,False,False,NaN,MX,from 11:40 to 11:50
6,3VDJQMaSWF0,2017-11-14,Demi Lovato Performs 'Sorry Not Sorry' / 'Tell...,MTV International,24,2017-11-12 23:40:32+00:00,"mtv|""uk""|""official""|""MTV EMAs 2017""|""MTV""|""MTV...",316360,16820,266,735,https://i.ytimg.com/vi/3VDJQMaSWF0/default.jpg,False,False,False,Demi Lovato performs Sorry Not Sorry and Tell ...,MX,from 23:40 to 23:50
7,IBd5v-MPEH4,2017-11-14,"Evangelio De Hoy 13 De Noviembre De 2017, Lect...",Tele VID,24,2017-11-13 03:00:00+00:00,"televida|""televid""|""lectio divina""|""evangelio ...",16963,777,14,41,https://i.ytimg.com/vi/IBd5v-MPEH4/default.jpg,False,False,False,Síguenos y haz parte de nuestro canal:\nYouTub...,MX,from 03:00 to 03:10
8,YxJB396gmWQ,2017-11-14,Así inició #AristeguiEnVivo este 13 de noviemb...,Aristegui Noticias,25,2017-11-13 14:59:29+00:00,"aristegui en vivo|""videos aristegui""|""aristegu...",37601,679,30,71,https://i.ytimg.com/vi/YxJB396gmWQ/default.jpg,False,False,False,Ver programa completo: http://aristeguinoticia...,MX,from 14:50 to 15:00
9,qlHi7uhZdvU,2017-11-14,Pelea Entre Los Coaches De La Voz México Y Una...,NZartreMexico,24,2017-11-11 21:01:59+00:00,"La Voz México|""La Voz México 2017""|""Ex timbiri...",149776,42,28,46,https://i.ytimg.com/vi/qlHi7uhZdvU/default.jpg,False,False,False,Pelea Entre Los Coaches De La Voz México Y Una...,MX,from 21:00 to 21:10
10,0k6gGxwNFSI,2017-11-14,Último adiós a Maru Dueñas y Claudio Reyes... ...,Imagen Entretenimiento,24,2017-11-13 15:21:21+00:00,"Sale el Sol|""Mauricio Barcelata""|""Luz Maria Ze...",5895,67,1,6,https://i.ytimg.com/vi/0k6gGxwNFSI/default.jpg,False,False,False,"Impactados por la noticia, Varios famosos desp...",MX,from 15:20 to 15:30
11,8_MFaKfSZUI,2017-11-14,MAQUILLAJE DRAMÁTICO Y ATRACTIVO PARA NOCHE.,Jeamileth Doll,22,2017-11-13 15:24:02+00:00,"JEAMILETH|""DOLL""|""@JEAMILETH""|""GURU""|""BELLEZA""...",46645,5500,104,855,https://i.ytimg.com/vi/8_MFaKfSZUI/default.jpg,False,False,False,"GRACIAS POR VERME!\nSI TE GUSTO DALE LIKE, COM...",MX,from 15:20 to 15:30
12,ag3qaxX6lW0,2017-11-14,7 Trucos Para CRECER DE ESTATURA Fácil y Rápido,Mr. Tops,24,2017-11-13 20:14:24+00:00,"trucos|""tricks""|""crecer""|""estatura""|""crecer de...",231503,35077,638,10188,https://i.ytimg.com/vi/ag3qaxX6lW0/default.jpg,False,False,False,Actualmente son muchísimas las personas que an...,MX,from 20:10 to 20:20
13,M4W-nrYGRYc,2017-11-14,ULTIMAS NOTICIAS HOY 13 DE NOVIEMBRE 2017. TER...,samm playHD Society,29,2017-11-12 22:25:55+00:00,"TERREMOTO EN IRAN HOY 2017|""TERREMOTO EN IRAK ...",75173,290,34,55,https://i.ytimg.com/vi/M4W-nrYGRYc/default.jpg,False,False,False,sismo en frontera con iran e irak hoy 2017.\nT...,MX,from 22:20 to 22:30
14,XDqZ57zAsGY,2017-11-14,Conocí a la Liga de la Justicia Completa en Pe...,EstoEs COMBO,1,2017-11-12 17:00:03+00:00,"la|""lata""|""combo""|""lalata""|""estoescombo""|""alex...",167066,9809,138,702,https://i.ytimg.com/vi/XDqZ57zAsGY/default.jpg,False,False,False,Ya estamos a nada para el estreno de esta movi...,MX,from 17:00 to 17:10
15,J5sgeaTui0w,2017-11-14,LA CUIN BICH (HISTORIAS DE TERROR),Relatos de Horror,1,2017-11-13 03:55:36+00:00,"Historias De Terror|""Relatos De Terror""|""Terro...",32201,1634,91,469,https://i.ytimg.com/vi/J5sgeaTui0w/default.jpg,False,False,False,Iniciamos la semana en Relatos De Horror con e...,MX,from 03:50 to 04:00
16,zR-9Pf-BBrM,2017-11-14,Dan el último adiós a Maru Dueñas y Claudio...,Hoy,24,2017-11-13 17:10:58+00:00,"Programa Hoy|""Televisa""|""Hoy""|""Canal De Las Es...",31145,283,20,29,https://i.ytimg.com/vi/zR-9Pf-BBrM/default.jpg,False,False,False,Familiares y amigos se dieron cita en una agen...,MX,from 17:10 to 17:20
17,mXmLxLCs9HA,2017-11-14,LEO | 13 AL 19 DE NOVIEMBRE | HORÓSCOPO SEMANA...,Alfonso León,24,2017-11-13 12:00:06+00:00,"alfonso leon|""horoscopo""|""tarot""|""mistico""|""zo...",13816,831,9,21,https://i.ytimg.com/vi/mXmLxLCs9HA/default.jpg,False,False,False,Bienvenidos con toda la mejor energía en esta ...,MX,from 12:00 to 12:10
18,bbFsQ3QuJAc,2017-11-14,Vuelo de la victoria final parte 1,tutosbells2,22,2017-11-13 02:35:52+00:00,"vuelo la victoria|""final""|""greatsnovels""",149799,816,167,95,https://i.ytimg.com/vi/bbFsQ3QuJAc/default.jpg,False,False,False,NaN,MX,from 02:30 to 02:40
19,3JMZx99Yb_0,2017-11-14,5 Experiencias extrañas vividas por repartidor...,MundoCreepy,24,2017-11-12 20:19:57+00:00,"fantasmas|""historias""|""leyendas""|""urbanas""|""na...",62550,6078,71,631,https://i.ytimg.com/vi/3JMZx99Yb_0/default.jpg,False,False,False,Muchos me insistieron bastante para que hicier...,MX,from 20:10 to 20:20

### 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [75]:
cluster_metrics = df_no_video_dup.groupby('cluster').agg(
    distinct_videos=('video_id', 'nunique'),
    avg_likes=('likes', 'mean'),
    avg_dislikes=('dislikes', 'mean')
)

cluster_metrics.head(144)

                     distinct_videos     avg_likes  avg_dislikes
cluster
from 00:00 to 00:10             1379  12049.622915   1013.228426
from 00:10 to 00:20              748   7256.143048    428.316845
from 00:20 to 00:30              652   7907.621166    648.645706
from 00:30 to 00:40              840   7619.203571    337.278571
from 00:40 to 00:50              640   8613.825000    485.631250
...                              ...           ...           ...
from 23:10 to 23:20              811   7447.773120    465.087546
from 23:20 to 23:30              731   9696.648427    608.588235
from 23:30 to 23:40              914   6520.680525    404.457330
from 23:40 to 23:50              744   9242.432796   1095.177419
from 23:50 to 00:00              692   5575.549133    384.816474

[144 rows x 3 columns]

### 8. For each tag, determine the number of videos
    Notice that tags contains a string with several tags.

In [76]:
# df_result['trending_date'] = pd.to_datetime(df_result['trending_date'], format='%y.%d.%m')
# df_result_ordered = df_result.sort_values(by=['trending_date'], ascending=[True])
# df_no_video_dup = df_result_ordered.drop_duplicates(subset=['video_id'], keep='last').reset_index(drop=True)

Here we explode the tags string column into a list of tags

In [77]:
tags_list = []
for tags in df_no_video_dup['tags']:
    tags_split = tags.split('|')
    for tag in tags_split:
        tag = tag.strip('"').strip("'")
        tags_list.append(tag)

In [78]:
print(tags_list[:20])

['20 Chistes malos que te harán reír', 'chistes malos', 'chistes', 'chistes graciosos', 'mejores chistes', 'los peores chistes', 'chistes jaimito', 'chistes sin gracia', 'chistes horribles', 'eljameshd', 'lomo de cerdo en salsa de moztaza', 'armando en tu cocina', 'lomo de cerdo', 'lomo de cerdo sin horno', 'lomo de cerdo en la estufa', 'lomo de cerdo a la moztaza', 'cena de navidad', 'cena de accion de gracias', 'peña nieto', 'epn']

In this cell, we count the number of occurrences of each tag using the Counter function, considering every time a tag appears, cause it corresponds to the number of related videos

In [79]:
tags_apperances = Counter(tags_list)
# convert the Counter object into a dataframe
df_tags_apperances = pd.DataFrame.from_dict(tags_apperances, orient='index', columns=['appearances'])

Here we noticed the presence of `[none]` tag

In [80]:
tags_apperances

Counter({'[none]': 23894,
         '2018': 5764,
         'funny': 4146,
         'comedy': 3104,
         'news': 3086,
         '2017': 2656,
         'video': 2077,
         'show': 2046,
         'tv': 1731,
         'television': 1717,
         'новости': 1551,
         'music': 1516,
         'humour': 1426,
         'политика': 1421,
         'юмор': 1412,
         'vlog': 1407,
         'humor': 1335,
         'TV': 1324,
         'обзор': 1312,
         'youtube': 1310,
         'review': 1302,
         'live': 1286,
         'football': 1270,
         'diy': 1255,
         'путин': 1225,
         'serial': 1209,
         'interview': 1158,
         'challenge': 1128,
         'rap': 1125,
         'News': 1122,
         'food': 1100,
         'politics': 1059,
         'DIY': 1052,
         'noticias': 1043,
         'top 10': 1022,
         'full episode': 999,
         'Россия': 993,
         'mexico': 989,
         'top': 987,
         'entertainment': 985,
         'drama': 967,
         '먹방': 965,
         'россия': 960,
         'new': 941,
         'trailer': 910,
         'funny videos': 903,
         'comedian': 892,
         'reaction': 889,
         'Comedy': 889,
         'film': 886,
         'fun': 877,
         'Путин': 872,
         'daily soap': 870,
         'watch online': 865,
         'tutorial': 855,
         'de': 845,
         'deutsch': 828,
         '문재인': 826,
         'приколы': 815,
         'atv': 797,
         'Entertainment': 795,
         'highlights': 793,
         'топ': 790,
         'game': 788,
         'sports': 774,
         'Televisa': 769,
         'love': 767,
         'viral': 763,
         'trump': 761,
         'talk show': 756,
         'funny video': 752,
         'breaking news': 751,
         'videos': 750,
         'how to': 748,
         'movie': 747,
         'best': 746,
         'top 5': 743,
         'sketch': 718,
         'vs': 717,
         'выборы': 713,
         'nba': 712,
         'Donald Trump': 704,
         'donald trump': 675,
         'beauty': 668,
         'celebrities': 656,
         'france': 654,
         'HD': 648,
         'dizi': 647,
         'cute': 645,
         'jokes': 642,
         'экономика': 639,
         'messi': 635,
         'tv azteca': 634,
         'clip': 624,
         'games': 623,
         '뉴스': 623,
         'своими руками': 623,
         'celebrity': 618,
         'test': 614,
         'последние новости': 610,
         'hollywood': 608,
         'animation': 608,
         'prank': 607,
         'makeup': 603,
         'science': 599,
         'basketball': 597,
         'german': 597,
         'шоу': 592,
         'Funny': 592,
         'прикол': 591,
         'Politics': 585,
         'youtuber': 584,
         'sport': 575,
         'fail': 570,
         'cat': 569,
         'hip hop': 562,
         'amor': 555,
         'cooking': 554,
         'family': 552,
         'latest news': 551,
         'Highlights': 549,
         'sp:ty=high': 547,
         'podcast': 545,
         'gameplay': 542,
         'сериал': 539,
         'Music': 538,
         'español': 535,
         'видео': 530,
         'comedia': 516,
         'hd': 512,
         '김정은': 512,
         'official': 510,
         'instagram': 505,
         'family friendly': 504,
         'Zee5': 504,
         'futbol': 502,
         'late night': 501,
         'кино': 494,
         'Trump': 493,
         'Tutorial': 490,
         'latest': 489,
         'divertissement': 486,
         'fashion': 486,
         'kids': 478,
         'izle': 477,
         'lol': 476,
         '料理': 476,
         'влог': 475,
         'Football': 473,
         'compilation': 472,
         '猫': 471,
         'Live': 470,
         'movies': 468,
         'react': 468,
         'famosos': 467,
         'india': 465,
         'anime': 463,
         'tips': 461,
         'unboxing': 461,
         'hindi': 455,
         'Noticias': 454,
         'интервью': 453,
         'tricks': 452,
         'joke': 452,
         'факты': 452,
         'media': 447,
         'Trailer': 446,
         '방탄소년단': 445,
         'freestyle': 445,
         'угар': 444,
         'dance': 444,
         'украина': 443,
         'entretenimiento': 442,
         'fox': 442,
         '트럼프': 442,
         'YouTube': 439,
         'trucos': 438,
         'любовь': 437,
         'Deutschland': 436,
         'lifestyle': 435,
         'подборка': 433,
         'Real Madrid': 431,
         'India': 431,
         'son': 430,
         'Reality TV': 429,
         'рецепт': 425,
         'radio': 423,
         'Rap': 423,
         'amlo': 422,
         'ronaldo': 422,
         'ток-шоу': 422,
         'mukbang': 418,
         'клип': 417,
         '철구': 416,
         'song': 416,
         'dog': 415,
         'travel': 415,
         'бизнес': 414,
         'BTS': 413,
         'hilarious': 410,
         'televisa': 409,
         'как приготовить': 409,
         'musique': 409,
         'talk': 407,
         'президент': 407,
         'онлайн': 405,
         'world': 405,
         'SAT.1': 405,
         'NBC': 401,
         'Украина': 399,
         'soccer': 399,
         'gaming': 398,
         'фильм': 397,
         'chismes': 396,
         'jabardasth': 396,
         'pop': 395,
         'comedy videos': 395,
         'police': 394,
         'おもしろ': 392,
         'resumen': 391,
         'foot': 391,
         'christmas': 388,
         'asmr': 387,
         'bts': 387,
         'CBS': 385,
         'CNN': 385,
         'рецепты': 384,
         'México': 384,
         'топ 10': 382,
         'culture': 382,
         'star tv': 381,
         'еда': 381,
         'лучшее': 380,
         'russia': 377,
         'marvel': 374,
         'disney': 373,
         'neymar': 373,
         'вести': 373,
         'авто': 373,
         '2016': 373,
         'TV show': 373,
         'extra jabardasth': 373,
         'кремль': 372,
         'лайфхаки': 372,
         'футбол': 371,
         'США': 371,
         'recipe': 370,
         'Pop': 369,
         'France': 369,
         'famous': 368,
         '박근혜': 367,
         'recetas': 365,
         'выборы 2018': 365,
         'ozee': 364,
         'ASMR': 364,
         '리뷰': 363,
         'paris': 363,
         'lustig': 363,
         'facebook': 363,
         'play': 362,
         'telugu': 361,
         '': 361,
         'goles': 360,
         'cover': 360,
         'шарий': 359,
         'отношения': 358,
         'дети': 358,
         'музыка': 357,
         'ufc': 356,
         'деньги': 355,
         'как сделать': 355,
         'amazing': 353,
         'highlight': 352,
         'the': 352,
         'kpop': 351,
         'Навальный': 351,
         'tuto': 351,
         'serie': 351,
         'enamorandonos': 350,
         'couple': 349,
         'promo': 347,
         'смешно': 347,
         'vidéo': 345,
         'celeb': 344,
         'AMLO': 344,
         'сделай сам': 344,
         'senegal': 343,
         'bollywood': 343,
         'iphone': 343,
         'NEWS': 341,
         'tops': 340,
         'essen': 340,
         'technology': 340,
         'SunTV': 339,
         'реакция': 338,
         'прямой эфир': 337,
         'かわいい': 337,
         'haul': 337,
         'yt:cc=on': 336,
         'daily': 336,
         'real madrid': 336,
         'Berlin': 336,
         '북한': 336,
         'curiosidades': 335,
         'français': 335,
         'Drama': 335,
         'replay': 332,
         'ニュース': 332,
         'amour': 331,
         'japan': 330,
         'смотреть': 329,
         'maroc': 329,
         'episode': 328,
         'грудинин': 326,
         'la': 325,
         'fortnite': 325,
         'Köln': 324,
         'laugh': 323,
         'Bundesliga': 322,
         'коррупция': 322,
         'アニメ': 322,
         'рэп': 321,
         'USA': 321,
         'chef': 319,
         'art': 318,
         '홍준표': 317,
         'fifa 18': 316,
         'apple': 316,
         'Canada': 316,
         'comida': 315,
         'AfD': 315,
         'morena': 314,
         'people': 314,
         'psg': 312,
         'fitness': 312,
         'ржака': 312,
         'meme': 311,
         'star': 309,
         'trending': 308,
         'лучшие приколы': 308,
         'wwe': 307,
         '워너원': 306,
         'crazy': 306,
         'musica': 305,
         'music video': 304,
         'satire': 303,
         'тв': 303,
         '밴쯔': 302,
         'debate': 302,
         'america': 301,
         'Soccer': 301,
         'Barcelona': 301,
         'comedic': 301,
         'YouTuber': 301,
         'Las Estrellas': 301,
         'Stephen Colbert': 300,
         'кризис': 298,
         'to': 298,
         'parody': 297,
         'المغرب': 297,
         'Cristiano Ronaldo': 296,
         'education': 294,
         'шутки': 294,
         'распаковка': 294,
         'ventaneando': 293,
         '자유한국당': 293,
         'battle': 293,
         'drole': 293,
         'en': 293,
         'google': 293,
         'lyrics': 292,
         '김어준': 292,
         'навальный': 292,
         'москва': 292,
         'série': 292,
         'manualidades': 292,
         'youtubers': 291,
         'real': 291,
         'комедия': 291,
         'Film': 291,
         'program': 291,
         'お笑い': 291,
         'wrestling': 290,
         'Sport': 290,
         '한국': 289,
         '대도서관': 289,
         '미국': 289,
         'Polizei': 289,
         '이명박': 288,
         'pri': 287,
         '釣り': 287,
         'en vivo': 285,
         'Vlog': 285,
         'жириновский': 285,
         'team': 285,
         'online': 285,
         'investigation': 285,
         '#youtube': 285,
         'mma': 284,
         'Interview': 284,
         'ねこ': 283,
         'Television': 283,
         '10': 281,
         'iphone x': 281,
         'lifehacks': 281,
         'memes': 280,
         'action': 279,
         'liga mx': 278,
         'Video': 278,
         'kochen': 278,
         'NBA': 277,
         'смех': 277,
         'трамп': 277,
         'recette': 277,
         'блог': 276,
         'zap': 276,
         'comment': 276,
         'theatre': 276,
         'TV Azteca': 276,
         'Colbert': 275,
         'михеев': 275,
         'Nachrichten': 275,
         'Telenovela': 275,
         '大食い': 275,
         'Top 10': 274,
         'самые': 274,
         'животные': 274,
         'владимир соловьев': 274,
         'Tipps': 274,
         'learn': 274,
         'fr': 274,
         'interviews': 273,
         'punjabi songs': 273,
         'life': 273,
         'наука': 273,
         'челлендж': 272,
         'up': 272,
         'astuces': 272,
         'host': 271,
         'сатановский': 271,
         'pan': 270,
         'Soap Opera': 270,
         'hiphop': 270,
         'новости дня': 269,
         'religion': 268,
         'новый год': 268,
         'рубль': 267,
         'politique': 267,
         'Wissen': 267,
         'PSG': 266,
         'NBC TV': 266,
         'lebron james': 266,
         'kino': 266,
         'sp:st=soccer': 266,
         'teaser': 265,
         '레전드': 265,
         'plays': 264,
         'Breaking News': 264,
         'series': 262,
         'Telemundo': 262,
         'korean': 262,
         'медведев': 262,
         'fifa': 262,
         'sp:vl=en-US': 261,
         'пранк': 261,
         'vlogs': 261,
         'lopez obrador': 259,
         'belleza': 259,
         'cuisine': 259,
         'creepy': 258,
         'elecciones 2018': 258,
         'twitter': 258,
         'fails': 258,
         'max': 258,
         'spanish': 258,
         '영화': 257,
         'канал': 257,
         'health': 257,
         'noticias de hoy': 256,
         '아이돌': 256,
         'шарий новое': 256,
         'Tricks': 256,
         'animals': 256,
         'в прямом эфире': 255,
         'шарий блог': 255,
         '대한민국': 254,
         'yeni dizi': 254,
         'Fußball': 254,
         '꿀잼': 254,
         'gol': 253,
         '可愛い': 253,
         'James Corden': 252,
         'tollywood': 252,
         'entrevista': 251,
         'barcelona': 251,
         'как': 251,
         'facts': 251,
         'télé réalité': 251,
         'of': 251,
         'animal': 251,
         'clash': 250,
         'пародия': 250,
         'roja': 250,
         'блогер': 250,
         'reviews': 249,
         'tendencias': 249,
         'divertido': 249,
         'ricardo anaya': 248,
         '청와대': 248,
         '아프리카': 247,
         'talent': 246,
         'women': 246,
         'премьера': 245,
         'топ 5': 245,
         'игры': 245,
         'Germany': 245,
         'backen': 245,
         'соловьев': 244,
         'Lionel Messi': 243,
         'reality': 243,
         'friends': 243,
         'mystery': 243,
         'famille': 243,
         'rire': 242,
         'fragman': 242,
         'BMW': 242,
         'conspiracy': 242,
         'новости россии': 242,
         'del': 241,
         'current affairs': 241,
         'Love': 241,
         'RT': 241,
         'kitchen': 241,
         'Fútbol': 240,
         'Dios': 240,
         '뉴스공장': 240,
         'celebrity news': 240,
         'Apple': 240,
         'experiment': 240,
         'анимация': 240,
         '動画': 240,
         'goals': 239,
         'Dokumentation': 239,
         'anchor anasuya': 239,
         'trap': 239,
         '#LasEstrellas': 239,
         'эхо москвы': 239,
         'BJ': 239,
         'life hacks': 238,
         'star wars': 238,
         'cinema': 238,
         'versus': 237,
         'JTBC': 237,
         '아프리카TV': 237,
         'naga babu': 237,
         'style': 237,
         'сегодня': 237,
         'советы': 237,
         'elhiwar ettounsi': 236,
         'عندي ما نقلك': 236,
         'president trump': 236,
         'car': 236,
         'avengers': 236,
         'kitten': 236,
         'ufo': 235,
         'james': 235,
         'idol': 235,
         '일본': 235,
         'etv comedy show': 235,
         'sab tv serials': 235,
         'do it yourself': 235,
         'comedy central': 235,
         'игра': 235,
         'japanese': 235,
         '爆笑': 235,
         '안철수': 234,
         'санкции': 234,
         'hkayet tounsia': 234,
         'denya okhra': 234,
         'oumour jedia': 234,
         'karim el gharbi': 234,
         'comedy show': 234,
         'sab tv channel': 234,
         'ゲーム': 234,
         '게임': 233,
         'korea': 233,
         'власть': 233,
         'мнение': 233,
         'митинг': 233,
         'кулинария': 233,
         'iPhone': 233,
         'labes': 233,
         'Politik': 233,
         'try not to laugh': 233,
         'current events': 233,
         'Goals': 232,
         'hit': 232,
         'actor': 232,
         'xazartv': 232,
         'xezertv': 232,
         'cook': 232,
         'andi mankolek': 232,
         'oumour jeddya': 232,
         'dari deco': 232,
         '360 degrees': 232,
         'klem ennes': 232,
         'ma binetna': 232,
         'maktoub': 232,
         'snl': 232,
         'world news': 232,
         'elecciones': 231,
         'vegan': 231,
         'liman yajroo fakat': 231,
         'labas': 231,
         'awled mofida': 231,
         'el hak maak': 231,
         'wled moufida': 231,
         'awled moufida': 231,
         'اليوم الثامن': 231,
         'مكتوب': 231,
         'أمور جدّية': 231,
         'أولاد مفيده': 231,
         'анатолий шарий': 231,
         'VLOG': 231,
         'turkey': 231,
         'slime': 231,
         'macron': 231,
         '고양이': 231,
         'eating': 230,
         'espn': 230,
         'happy nes': 230,
         'lifehack': 230,
         'Star': 230,
         '4k': 230,
         'Telugu News': 230,
         'The Late Show': 230,
         'Late Show': 230,
         'dinero': 229,
         'upsc': 229,
         'telugu news': 229,
         '衝撃': 229,
         'manga': 228,
         '중국': 228,
         'school': 228,
         'ток шоу': 228,
         'nachrichten': 228,
         'android': 227,
         '양띵': 227,
         'Official': 226,
         'moto': 226,
         'clips': 226,
         'comedy skits in telugu': 226,
         'cartoon': 226,
         'сша': 225,
         'racha ravi': 225,
         '50667': 225,
         'レシピ': 225,
         'easy': 224,
         'Late Late Show': 224,
         'история': 224,
         'собчак': 224,
         'comedy channel india': 224,
         'jethalal': 224,
         'logan paul': 224,
         'cristiano ronaldo': 224,
         'tag': 223,
         'nuevo': 223,
         'The Late Late Show': 223,
         'Corden': 223,
         'камикадзе': 223,
         'Обзор': 223,
         'BuzzFeed': 223,
         'how to make': 223,
         'peña nieto': 222,
         'спорт': 222,
         'francais': 222,
         'wrestler': 222,
         'netflix': 222,
         'tv show': 222,
         'интересные факты': 222,
         'completo': 221,
         '김어준의 뉴스공장': 221,
         'songs': 221,
         'programme': 221,
         'TPMP': 221,
         'comedy short films': 221,
         'La Liga': 220,
         'vida': 220,
         'yeni bölüm': 220,
         'babita': 220,
         'fine brothers entertainment': 220,
         'trevor noah': 220,
         'Johnny Hallyday': 220,
         'documentary': 219,
         'azerbaycan': 219,
         'rhett and link': 219,
         'fine brothers': 219,
         'best of': 219,
         'berlin': 219,
         'Skills': 218,
         'интересное': 218,
         'الجزائر': 218,
         'ifhbq': 218,
         'толя шарий': 218,
         'thefinebros': 218,
         'the daily show': 218,
         'nba highlights': 218,
         'samsung': 217,
         'шарий анатолий': 217,
         'видео шария': 217,
         'watch': 217,
         '面白': 217,
         'crafts': 217,
         'madrid': 216,
         'türkiye': 216,
         'web series': 216,
         'алиэкспресс': 216,
         'reflexiones': 215,
         'новое видео шарий': 215,
         'aliexpress': 215,
         'comics': 214,
         'season': 214,
         'cristiano': 214,
         'stand-up': 214,
         'candy': 214,
         'business': 214,
         'Review': 213,
         'FBE': 213,
         'fichajes': 213,
         'tutoriel': 213,
         'espectaculos': 212,
         'nhar lahad ma hemek fi had': 212,
         'sami fehri': 212,
         'نهار الأحد ما يهمّك في حدّ': 212,
         'نهار الأحد': 212,
         'wrestle': 211,
         'trends': 211,
         'smartphone': 210,
         'Москва': 210,
         'comedy channel hindi': 210,
         'cruz azul': 210,
         'super': 209,
         'motivacion': 209,
         'Goles': 209,
         'actualité': 209,
         'tech': 209,
         'fußball': 209,
         'taarak mehta ka ooltah chashmah': 209,
         'cocina': 209,
         'смешные видео': 209,
         'vlogger': 208,
         'dessert': 208,
         'ржач': 208,
         'Грудинин': 208,
         'Disney': 207,
         '손석희': 207,
         'top5': 207,
         'drôle': 207,
         'Talk Show': 207,
         'PRI': 207,
         'usa': 206,
         'reactions': 206,
         'space': 206,
         'новое': 206,
         '평창올림픽': 206,
         'رمضان 2018': 206,
         'wissen': 205,
         'tipps': 205,
         'hindi shows': 205,
         'Taarak Mehta': 205,
         'exatlon': 205,
         'salud': 204,
         'Futebol': 204,
         'ZDF': 204,
         'actress': 204,
         'MSNBC': 204,
         'breaking': 204,
         'game highlights': 204,
         'ps4': 204,
         '#ConLasEstrellas': 203,
         'Resumen': 203,
         'jose antonio meade': 203,
         'Fail': 203,
         'новости мира': 203,
         'серия': 203,
         'Russia': 203,
         'party': 203,
         'vine': 203,
         'uzbek': 203,
         '웃긴': 203,
         'مصارعه': 202,
         '장난감': 202,
         '韓国': 202,
         'FIFA 18': 201,
         'Новости': 201,
         'incroyable': 201,
         'world wrestling entertainment': 201,
         'कुश्ती': 201,

In [81]:
df_tags_apperances.sort_values(by='appearances', ascending=False).head()

        appearances
[none]        23894
2018           5764
funny          4146
comedy         3104
news           3086

### 9. Find the tags with the largest number of videos

For this step, we simply selected the top 5 tags from the previous result, excluding the tag `[none]`.

In [82]:
df_tags_apperances = df_tags_apperances.sort_values(by='appearances', ascending=False)
print(df_tags_apperances[1:6])

        appearances
2018           5764
funny          4146
comedy         3104
news           3086
2017           2656

### 10. For each (tag, country) pair, compute average ratio likes/dislikes

Similar to point 8, we explode the tags string column into a list of tags mantainig the relationship between the tag and the video

In [83]:
df_no_video_dup['tag_list'] = df_no_video_dup['tags'].apply(lambda x: [tag.strip('"').strip("'") for tag in x.split('|')])

Explode the dataframe, so that each tag is a row

    We decided to mantain [none] values in order to also analyse the performance of no-tag videos.

In [84]:
df_exploded_tags = df_no_video_dup.explode('tag_list').reset_index(drop=True)
# some faulty records where created by the presence of the double pipe 
df_exploded_tags = df_exploded_tags[df_exploded_tags['tag_list'] != ''].reset_index(drop=True)
# df_exploded_tags = df_exploded_tags[df_exploded_tags['tag_list'] != '[none]']
df_exploded_tags.info()
df_exploded_tags.head()

<class 'pandas.DataFrame'>
RangeIndex: 2997383 entries, 0 to 2997382
Data columns (total 19 columns):
 #   Column                  Dtype
---  ------                  -----
 0   video_id                str
 1   trending_date           datetime64[us]
 2   title                   str
 3   channel_title           str
 4   category_id             int64
 5   publish_time            datetime64[us, UTC]
 6   tags                    str
 7   views                   int64
 8   likes                   int64
 9   dislikes                int64
 10  comment_count           int64
 11  thumbnail_link          str
 12  comments_disabled       bool
 13  ratings_disabled        bool
 14  video_error_or_removed  bool
 15  description             str
 16  country                 str
 17  cluster                 str
 18  tag_list                str
dtypes: bool(3), datetime64[us, UTC](1), datetime64[us](1), int64(5), str(9)
memory usage: 374.5 MB

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,cluster,tag_list
0,y5wvD7QH1x4,2017-11-14,20 Chistes malos que te harán reír #12,ElJamesHD Tops,24,2017-11-12 19:00:04+00:00,"20 Chistes malos que te harán reír|""chistes ma...",299832,44011,1213,14355,https://i.ytimg.com/vi/y5wvD7QH1x4/default.jpg,False,False,False,Descarga la app: http://bit.do/ElJamesHDTops_Y...,MX,from 19:00 to 19:10,20 Chistes malos que te harán reír
1,y5wvD7QH1x4,2017-11-14,20 Chistes malos que te harán reír #12,ElJamesHD Tops,24,2017-11-12 19:00:04+00:00,"20 Chistes malos que te harán reír|""chistes ma...",299832,44011,1213,14355,https://i.ytimg.com/vi/y5wvD7QH1x4/default.jpg,False,False,False,Descarga la app: http://bit.do/ElJamesHDTops_Y...,MX,from 19:00 to 19:10,chistes malos
2,y5wvD7QH1x4,2017-11-14,20 Chistes malos que te harán reír #12,ElJamesHD Tops,24,2017-11-12 19:00:04+00:00,"20 Chistes malos que te harán reír|""chistes ma...",299832,44011,1213,14355,https://i.ytimg.com/vi/y5wvD7QH1x4/default.jpg,False,False,False,Descarga la app: http://bit.do/ElJamesHDTops_Y...,MX,from 19:00 to 19:10,chistes
3,y5wvD7QH1x4,2017-11-14,20 Chistes malos que te harán reír #12,ElJamesHD Tops,24,2017-11-12 19:00:04+00:00,"20 Chistes malos que te harán reír|""chistes ma...",299832,44011,1213,14355,https://i.ytimg.com/vi/y5wvD7QH1x4/default.jpg,False,False,False,Descarga la app: http://bit.do/ElJamesHDTops_Y...,MX,from 19:00 to 19:10,chistes graciosos
4,y5wvD7QH1x4,2017-11-14,20 Chistes malos que te harán reír #12,ElJamesHD Tops,24,2017-11-12 19:00:04+00:00,"20 Chistes malos que te harán reír|""chistes ma...",299832,44011,1213,14355,https://i.ytimg.com/vi/y5wvD7QH1x4/default.jpg,False,False,False,Descarga la app: http://bit.do/ElJamesHDTops_Y...,MX,from 19:00 to 19:10,mejores chistes

In [85]:
# df_exploded_tags[df_exploded_tags['tag_list'] == '[none]']

In [86]:
df_tags_country_ratio = df_exploded_tags.groupby(['tag_list', 'country']).agg(
    sum_likes = ('likes', 'sum'),
    sum_dislikes = ('dislikes', 'sum')
)

In [87]:
df_tags_country_ratio['like_ratio'] = np.where(
    df_tags_country_ratio['sum_dislikes'] == 0,
    df_tags_country_ratio['sum_likes'], 
    df_tags_country_ratio['sum_likes'] / df_tags_country_ratio['sum_dislikes']
)
df_tags_country_ratio.head()

                         sum_likes  sum_dislikes  like_ratio
tag_list        country
#Freeticket     IN            3085          1162    2.654905
#GST            IN            2632          1089    2.416896
#Jaisimha       IN            3085          1162    2.654905
#JanaSenaParty  IN            4729           276   17.134058
#MahaaNews      IN            2048           246    8.325203

### 11. For each (trending_date, country) pair, the video with the largest number of views

In [88]:
df_bestvid_per_country_date = df_no_video_dup.loc[df_no_video_dup.groupby(['country', 'trending_date'])['views'].idxmax(), 
                                                  ['trending_date', 'country', 'video_id', 'title', 'views']].reset_index(drop=True)
df_bestvid_per_country_date.head(20)

,trending_date,country,video_id,title,views
0,2017-11-14,CA,exMNBvwCfRY,LES PIRES DOUBLAGES FRANÇAIS,3641421
1,2017-11-15,CA,f-UzOpuKOVY,Fukrey Returns | Trailer | Pulkit Samrat | Var...,5792827
2,2017-11-16,CA,JzCsM1vtn78,THE LOGANG MADE HISTORY. LOL. AGAIN.,5085080
3,2017-11-17,CA,1SiKopOt-QM,26 SIMPLE WAYS TO SPEED UP YOUR EVERYDAY ROUTINE,5277237
4,2017-11-18,CA,Ehke7aPI9l0,Kurt Angle & The Shield lead a Raw raid of Sma...,4799436
5,2017-11-19,CA,VsYmwBOYfW8,Mean Tweets – Jimmy Kimmel Edition,4738425
6,2017-11-20,CA,E8B1c3NpLpc,Miss World 2017 - Crowning Moment,7664480
7,2017-11-21,CA,om-_yJaSW_Y,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,1197269
8,2017-11-22,CA,FGAfZ-PTaNU,"$1,977 Japanese Grapes",2915115
9,2017-11-23,CA,wlS6Ix7mA0w,Anitta & J Balvin - Downtown | Official Music ...,9004469
10,2017-11-24,CA,GxkLy_mvGXE,Walk On Water/Stan/Love The Way You Lie (Medle...,3783206
11,2017-11-25,CA,MG-bvSY2f_4,The Sacred Riana Semi-Final 2 – VOTE NOW | Asi...,4649138
12,2017-11-26,CA,0YZvOTas8h0,OUR LITTLE BROTHER VS SISTER GYMNASTICS BATTLE!,2894524
13,2017-11-27,CA,VJwoSfTOhyM,Water Bottle Flip 2 | Dude Perfect,13963525
14,2017-11-28,CA,RSRzIrOqaN4,"Romeo Santos, Daddy Yankee, Nicky Jam - Bella ...",17208914
15,2017-11-29,CA,unk6n3_QdlM,STUNG by a WARRIOR WASP!,5305409
16,2017-11-30,CA,H6tFxphsZQs,MANKIRT AULAKH - JATT DI CLIP (Full Song) Dj F...,2462199
17,2017-12-01,CA,TCoZstGksJ8,10 Times The Pawn Stars Got Scammed,3765943
18,2017-12-02,CA,QREWcgbMSxA,WolfieRaps - Check the Statistics Feat. Ricegu...,5777201
19,2017-12-03,CA,vzNcSvKCOyA,Varus: As We Fall [OFFICIAL MUSIC VIDEO] | Lea...,2452418

### 12. Divide trending_date into three columns: year, month, day

In [89]:
df_result['year'] = df_result['trending_date'].dt.year
df_result['month'] = df_result['trending_date'].dt.month
df_result['day'] = df_result['trending_date'].dt.day
df_result.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,year,month,day
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,2017,11,14
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,2017,11,14
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,2017,11,14
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,2017,11,14
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,2017,11,14

### 13. For each (month, country) pair, the video with the largest number of views

In [90]:
df_bestvid_per_country_month = df_result.loc[df_result.groupby(['country', 'month'], as_index = True)['views'].idxmax(), 
                                                  ['month', 'country', 'video_id', 'title', 'views']].reset_index(drop=True)
df_bestvid_per_country_month

,month,country,video_id,title,views
0,1,CA,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,43067983
1,2,CA,BhIEIO0vaBE,To Our Daughter,51243149
2,3,CA,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,61163906
3,4,CA,u9Mv98Gr5pY,VENOM - Official Trailer (HD),53071887
4,5,CA,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,98938809
...,...,...,...,...,...
72,4,US,ffxKSjUwKdU,Ariana Grande - No Tears Left To Cry,74523616
73,5,US,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,217750076
74,6,US,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,225211923
75,11,US,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",102012605
76,12,US,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,149376127

    we decided to also evaluate the correlation between month-year ancd country, more useful for trend analysis

In [91]:
df_bestvid_per_country_monthyear = df_result.loc[
    df_result.groupby(['country', 'year', 'month'], as_index=True)['views'].idxmax(),
    ['year', 'month', 'country', 'video_id', 'title', 'views']
].reset_index(drop=True)

df_bestvid_per_country_monthyear

,year,month,country,video_id,title,views
0,2017,11,CA,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",56843038
1,2017,12,CA,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,137843120
2,2018,1,CA,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,43067983
3,2018,2,CA,BhIEIO0vaBE,To Our Daughter,51243149
4,2018,3,CA,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,61163906
...,...,...,...,...,...,...
72,2018,2,US,BhIEIO0vaBE,To Our Daughter,56111957
73,2018,3,US,-BQJo3vK8O8,Maluma - El Préstamo (Official Video),87264467
74,2018,4,US,ffxKSjUwKdU,Ariana Grande - No Tears Left To Cry,74523616
75,2018,5,US,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,217750076
76,2018,6,US,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,225211923

### 14. Read all json files with the video categories

While reading the json files, we also take the opportunity to create a dataframe useful for the next step

In [92]:
df_categories = pd.DataFrame()

# iterate over all files in the data folder and select only the category json files
for files in os.listdir(data_dir):
    if files.endswith(".json"):
        file_path = os.path.join(data_dir, files)
        # load the json containing the video categories
        with open(file_path, 'r', encoding='utf-8', errors='replace') as json_file:
            data = json.load(json_file)
        # take only the category id and the snippet key (which contains the label/title and the assignable flag)
        df_category_temp = pd.DataFrame(data['items']).get(['id', 'snippet'])
        df_category_temp['country'] = files[:2] # Get country from filename
        df_categories = pd.concat([df_categories, df_category_temp]).reset_index(drop=True)

# extract the category label and the assignable flag
df_categories['category'] = df_categories['snippet'].apply(lambda x: x.get('title') if isinstance(x, dict) else None)
df_categories['assignable'] = df_categories['snippet'].apply(lambda x: x.get('assignable') if isinstance(x, dict) else None)

df_categories.drop(columns=['snippet'], inplace=True)

In [93]:
df_categories

     id country          category  assignable
0     1      CA  Film & Animation        True
1     2      CA  Autos & Vehicles        True
2    10      CA             Music        True
3    15      CA    Pets & Animals        True
4    17      CA            Sports        True
..   ..     ...               ...         ...
306  40      US    Sci-Fi/Fantasy       False
307  41      US          Thriller       False
308  42      US            Shorts       False
309  43      US             Shows       False
310  44      US          Trailers       False

[311 rows x 4 columns]

### 15. For each country, determine how many videos have a category that is not assignable.

In [94]:
df_no_video_country_dup = df_result_ordered.drop_duplicates(subset=['video_id', 'country'], keep='last').reset_index(drop=True)

Map the assignable flag to the category id using the category dataframe

In [95]:
df_no_video_country_dup['assignable'] = df_no_video_country_dup['category_id'].astype(str).map(
    df_categories.drop_duplicates('id').set_index('id')['assignable']
)

In [96]:
# df_no_video_country_dup.loc[df_no_video_country_dup['assignable'] == 1, ['video_id', 'category_id', 'assignable']].head()

In [97]:
df_video_counts = df_no_video_country_dup[df_no_video_country_dup['assignable'] == 0].groupby('country')['video_id'].count()
df_video_counts

country
CA    111
DE    105
FR    107
GB      1
IN    123
KR     74
MX      3
RU    168
US      4
Name: video_id, dtype: int64